# Generated by Django 4.1.11 on 2023-10-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
